### ISSUE TITLE
add ability to specify grain estimate file

### ISSUE THREAD

**Issue by ddale** [praxes/hexrd#46]
We need to be able to specify a grain file to be used as an estimate, so we can feed the output forward to subsequent analysis steps. The flow in execution would be: if the file exists: load it as the preliminary estimate, if it does not, use the defaults. If the file exists, should we skip the first iteration in the fitgrains analysis (loose tolerances)?

Then in yaml:

``` yaml
analysis_name: first

---
analysis_name:second 
fit_grains:
  estimate: first/grains.out
```
